
replicas: 1 # for better debugging experience
controller:
  env:
    # Azure client settings
    - name: ARM_SUBSCRIPTION_ID
      value: ed4bb153-37db-4f9e-99b0-dc0f00cd8be3
    - name: LOCATION
      value: canadacentral
    - name: AZURE_CLUSTER_NAME
      value: rkaksdev
    - name: AZURE_NODE_RESOURCE_GROUP
      value: MC_aks-solution_rkaksdev_canadacentral
    - name: ARM_RESOURCE_GROUP
      value: aks-solution
    - name: LEADER_ELECT # disable leader election for better debugging experience
      value: "false"
    - name: E2E_TEST_MODE
      value: "false"
workloadIdentity:
  clientId: 51d17879-600f-4427-abf9-58adb04c3252
  tenantId: d4697920-75d5-4b07-bdbb-ca7abb88444d
